// Generated by CoffeeScript 1.3.3
(function() {
  var NMinStep, NNoise, NWalk, NWalkDistance, d2, dim, doOnce, initialized, noiseVals, noiseWalk;

  initialized = false;

  dim = 1024;

  d2 = dim * dim;

  NNoise = 30000;

  noiseVals = [NNoise];

  NWalkDistance = 30;

  NMinStep = 1;

  NWalk = 2000;

  noiseWalk = [NWalk];

  (doOnce = function() {
    var currentTime, i, rval, t1;
    currentTime = new Date();
    t1 = currentTime.getTime();
    initialized = true;
    i = 0;
    while (i < NNoise) {
      rval = Math.random();
      if (i < NWalk) {
        noiseWalk[i] = Math.round(rval * NWalkDistance + NMinStep);
      }
      noiseVals[i++] = Math.round(rval * 255);
    }
    return console.log('init time', currentTime.getTime() - t1);
  })();

  $(function() {
    var b, canvas, ctx, currentTime, i, iHeight, iNoise, iNoiseWalk, iWidth, id, j, scaleHeight, scaleWidth, screenHeight, screenWidth, t1;
    canvas = window.document.getElementById("bkgCanvas");
    console.log(canvas);
    if (canvas && canvas.getContext) {
      iWidth = iHeight = dim;
      screenWidth = $(window).width();
      screenHeight = $(window).height();
      scaleWidth = $(window).width() / iWidth;
      scaleHeight = $(window).height() / iHeight;
      canvas.width = iWidth;
      canvas.height = iHeight;
      ctx = canvas.getContext("2d");
      id = ctx.getImageData(0, 0, iWidth, iHeight);
      b = id.data;
      currentTime = new Date();
      t1 = currentTime.getTime();
      i = iNoise = iNoiseWalk = 0;
      while (i < d2) {
        j = i * 4;
        b[j] = b[j + 1] = b[j + 2] = noiseVals[iNoise];
        b[j + 3] = 255;
        iNoise++;
        if (iNoise >= NNoise) {
          iNoise = 0;
        }
        iNoiseWalk++;
        if (iNoiseWalk >= NWalk) {
          iNoiseWalk = 0;
        }
        i += noiseWalk[iNoiseWalk];
      }
      ctx.putImageData(id, 0, 0);
      return console.log('total time', currentTime.getTime() - t1);
    }
  });

}).call(this);
