// Generated by CoffeeScript 1.6.3
(function() {
  var NMinStep, NWalk, NWalkDistance, d2, dim, initialized, noiseWalk;

  initialized = false;

  dim = 1024;

  d2 = dim * dim;

  NWalkDistance = 60;

  NMinStep = 1;

  NWalk = 2000;

  noiseWalk = [];

  noiseWalk.length = NWalk;

  $(function() {
    var init, setCanvas, t1;
    t1 = Date.now();
    init = function(cb) {
      var i, rval;
      initialized = true;
      i = 0;
      while (i < NWalk) {
        rval = Math.random();
        noiseWalk[i++] = Math.round(rval * NWalkDistance + NMinStep);
      }
      console.log('init time', Date.now() - t1);
      return cb();
    };
    setCanvas = function() {
      var b, canvas, ctx, i, iNoiseWalk, id, j, t2,
        _this = this;
      t2 = Date.now();
      canvas = window.document.getElementById("bkgCanvas");
      if (canvas && canvas.getContext) {
        ctx = canvas.getContext("2d");
        ctx.fillStyle = '#000';
        ctx.fillRect(0, 0, dim, dim);
        id = ctx.getImageData(0, 0, dim, dim);
        b = id.data;
        i = 0;
        iNoiseWalk = Math.round(Math.random() * NWalk);
        while (i < d2) {
          j = i * 4;
          b[j] = b[j + 1] = b[j + 2] = Math.round(Math.random() * 255);
          b[j + 3] = 255;
          iNoiseWalk++;
          if (iNoiseWalk >= NWalk) {
            iNoiseWalk = 0;
          }
          i += noiseWalk[iNoiseWalk];
        }
        ctx.putImageData(id, 0, 0);
        console.log('total time', Date.now() - t1, 'noise apply time', Date.now() - t2);
        setTimeout(function() {
          setCanvas();
          return false;
        }, 50);
      }
      return false;
    };
    return init(setCanvas);
  });

}).call(this);
